drop table Priloga_clan cascade constraints;
drop table CERTIFIKAT_proizvod cascade constraints;
drop table CERTIFIKAT_priloga_proizvod cascade constraints;
drop table CERTIFIKAT_priloga_clan cascade constraints;
drop table Priloga cascade constraints;
drop table ProizvodKolicine cascade constraints;
drop table Certifikat cascade constraints;
drop table ZASCITNIZNAK_proizvod cascade constraints;
drop table ZascitniZnak cascade constraints;
drop table Proizvod cascade constraints;
drop table ZakonskaPodlaga cascade constraints;
drop table Dejavnost cascade constraints;
drop table Uporabnik_pravice cascade constraints;
drop table Uporabnik cascade constraints;
drop table Pravica cascade constraints;
drop table Subjekt cascade constraints;
drop table ZascitenProizvod cascade constraints;
drop table Shema cascade constraints;


CREATE TABLE "ESK_DATA"."ZAKONSKAPODLAGA" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	STEVILKA VARCHAR2(2000),
	VSEBINA CLOB,
	CONSTRAINT PK_ZAKONSKAPODLAGA_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."SHEMA" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	NAZIV VARCHAR2(2000),
	CONSTRAINT PK_SHEMA_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."ZASCITENPROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	NAZIV VARCHAR2(2000),
	CONSTRAINT PK_ZASCITENPROIZVOD_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."PROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	NAZIV VARCHAR2(2000),
	ID_SHEMA NUMBER NOT NULL,
	ID_ZAKONSKA_PODLAGA NUMBER NOT NULL,
	ID_ZASCITEN_PROIZVOD NUMBER NOT NULL,
	CONSTRAINT PK_PROIZVOD_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."PROIZVOD" 
ADD CONSTRAINT "FK_PROIZVODSHEMAID_SHEMA"
   FOREIGN KEY (ID_SHEMA)
   REFERENCES "SHEMA" (ID);

ALTER TABLE "ESK_DATA"."PROIZVOD" 
ADD CONSTRAINT "FK_PROIZVODZAKONSKAPODLAGAID_ZAKONSKA_PODLAGA"
   FOREIGN KEY (ID_ZAKONSKA_PODLAGA)
   REFERENCES "ZAKONSKAPODLAGA" (ID);

ALTER TABLE "ESK_DATA"."PROIZVOD" 
ADD CONSTRAINT "FK_PROIZVODZASCITENPROIZVODID_ZASCITEN_PROIZVOD"
   FOREIGN KEY (ID_ZASCITEN_PROIZVOD)
   REFERENCES "ZASCITENPROIZVOD" (ID);


CREATE TABLE "ESK_DATA"."SUBJEKT" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	KMGMID VARCHAR2(2000) NULL,
	IME VARCHAR2(2000) NULL,
	PRIIMEK VARCHAR2(2000) NULL,
	NAZIV VARCHAR2(2000) NULL,
	NASLOV VARCHAR2(2000),
	MATICNA VARCHAR2(2000) NULL,
	DAVCNA VARCHAR2(2000) NULL,
	ID_POSTE VARCHAR2(2000),
	POSTA VARCHAR2(2000),
	TEL_ST VARCHAR2(2000) NULL,
	EMAIL VARCHAR2(2000) NULL,
	CONSTRAINT PK_SUBJEKT_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."PRAVICA" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	NAZIV VARCHAR2(2000),
	TIP VARCHAR2(2000),
	CONSTRAINT PK_PRAVICA_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."UPORABNIK" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	UPORABNISKO_IME VARCHAR2(2000),
	IME VARCHAR2(2000),
	PRIIMEK VARCHAR2(2000),
	ORGANIZACIJA VARCHAR2(2000),
	TOKEN VARCHAR2(2000),
	CONSTRAINT PK_UPORABNIK_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."UPORABNIK_PRAVICE" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_UPORABNIK NUMBER,
	ID_PRAVICA NUMBER,
	CONSTRAINT PK_UPORABNIK_PRAVICE_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."UPORABNIK_PRAVICE" 
ADD CONSTRAINT "FK_UPORABNIK_PRAVICEUPORABNIKID_UPORABNIK"
   FOREIGN KEY (ID_UPORABNIK)
   REFERENCES "UPORABNIK" (ID);

ALTER TABLE "ESK_DATA"."UPORABNIK_PRAVICE" 
ADD CONSTRAINT "FK_UPORABNIK_PRAVICEPRAVICAID_PRAVICA"
   FOREIGN KEY (ID_PRAVICA)
   REFERENCES "PRAVICA" (ID);


CREATE TABLE "ESK_DATA"."DEJAVNOST" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	NAZIV VARCHAR2(2000),
	CONSTRAINT PK_DEJAVNOST_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."ZASCITNIZNAK" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ZZ_SHEMA VARCHAR2(2000) NULL,
	NAZIV_PROIZVODA VARCHAR2(2000) NULL,
	DAT_ODL DATE NULL,
	ST_ODL VARCHAR2(2000) NULL,
	CERT_ORGAN VARCHAR2(2000) NULL,
	ID_IMETNIK NUMBER NOT NULL,
	ID_SHEMA NUMBER NOT NULL,
	ID_ZASCITEN_PROIZVOD NUMBER NOT NULL,
	CONSTRAINT PK_ZASCITNIZNAK_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."ZASCITNIZNAK" 
ADD CONSTRAINT "FK_ZASCITNIZNAKSUBJEKTID_IMETNIK"
   FOREIGN KEY (ID_IMETNIK)
   REFERENCES "SUBJEKT" (ID);

ALTER TABLE "ESK_DATA"."ZASCITNIZNAK" 
ADD CONSTRAINT "FK_ZASCITNIZNAKSHEMAID_SHEMA"
   FOREIGN KEY (ID_SHEMA)
   REFERENCES "SHEMA" (ID);

ALTER TABLE "ESK_DATA"."ZASCITNIZNAK" 
ADD CONSTRAINT "FK_ZASCITNIZNAKZASCITENPROIZVODID_ZASCITEN_PROIZVOD"
   FOREIGN KEY (ID_ZASCITEN_PROIZVOD)
   REFERENCES "ZASCITENPROIZVOD" (ID);


CREATE TABLE "ESK_DATA"."ZASCITNIZNAK_PROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_ZASCITNIZNAK NUMBER,
	ID_PROIZVOD NUMBER,
	CONSTRAINT PK_ZASCITNIZNAK_PROIZVOD_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."ZASCITNIZNAK_PROIZVOD" 
ADD CONSTRAINT "FK_ZASCITNIZNAK_PROIZVODZASCITNIZNAKID_ZASCITNIZNAK"
   FOREIGN KEY (ID_ZASCITNIZNAK)
   REFERENCES "ZASCITNIZNAK" (ID);

ALTER TABLE "ESK_DATA"."ZASCITNIZNAK_PROIZVOD" 
ADD CONSTRAINT "FK_ZASCITNIZNAK_PROIZVODPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);


CREATE TABLE "ESK_DATA"."CERTIFIKAT" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	TIP VARCHAR2(2000),
	STEVILKA VARCHAR2(2000),
	DAT_KONTROLE DATE NULL,
	DAT_IZDAJE DATE NULL,
	DAT_VELJ DATE NULL,
	STATUS VARCHAR2(2000),
	TEL_ST VARCHAR2(2000) NULL,
	EMAIL VARCHAR2(2000) NULL,
	OPOMBA CLOB NULL,
	DAT_VNOSA DATE,
	KONTROLOR VARCHAR2(2000),
	ID_SHEMA NUMBER NOT NULL,
	ID_ZASCITEN_PROIZVOD NUMBER NOT NULL,
	ID_PROIZVOD NUMBER NOT NULL,
	ID_IMETNIK NUMBER NOT NULL,
	ID_UPORABNIK NUMBER NOT NULL,
	ID_DEJAVNOST NUMBER NOT NULL,
	CONSTRAINT PK_CERTIFIKAT_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATSHEMAID_SHEMA"
   FOREIGN KEY (ID_SHEMA)
   REFERENCES "SHEMA" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATZASCITENPROIZVODID_ZASCITEN_PROIZVOD"
   FOREIGN KEY (ID_ZASCITEN_PROIZVOD)
   REFERENCES "ZASCITENPROIZVOD" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATSUBJEKTID_IMETNIK"
   FOREIGN KEY (ID_IMETNIK)
   REFERENCES "SUBJEKT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATUPORABNIKID_UPORABNIK"
   FOREIGN KEY (ID_UPORABNIK)
   REFERENCES "UPORABNIK" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATDEJAVNOSTID_DEJAVNOST"
   FOREIGN KEY (ID_DEJAVNOST)
   REFERENCES "DEJAVNOST" (ID);


CREATE TABLE "ESK_DATA"."PROIZVODKOLICINE" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	VREDNOST NUMBER,
	ENOTA VARCHAR2(2000) NULL,
	LETO NUMBER,
	ID_PROIZVOD NUMBER NOT NULL,
	ID_CERTIFIKAT NUMBER NOT NULL,
	CONSTRAINT PK_PROIZVODKOLICINE_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."PROIZVODKOLICINE" 
ADD CONSTRAINT "FK_PROIZVODKOLICINEPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);

ALTER TABLE "ESK_DATA"."PROIZVODKOLICINE" 
ADD CONSTRAINT "FK_PROIZVODKOLICINECERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);


CREATE TABLE "ESK_DATA"."PRILOGA" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	STEVILKA VARCHAR2(2000),
	DAT_IZDAJE DATE,
	DAT_VELJ DATE,
	STATUS VARCHAR2(2000),
	VSEBINA CLOB NULL,
	CONSTRAINT PK_PRILOGA_ID PRIMARY KEY (ID)
);

CREATE TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_CLAN" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_CERTIFIKAT NUMBER,
	ID_PRILOGA NUMBER,
	CONSTRAINT PK_CERTIFIKAT_PRILOGA_CLAN_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_CLAN" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_CLANCERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_CLAN" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_CLANPRILOGAID_PRILOGA"
   FOREIGN KEY (ID_PRILOGA)
   REFERENCES "PRILOGA" (ID);


CREATE TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_PROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_CERTIFIKAT NUMBER,
	ID_PRILOGA NUMBER,
	CONSTRAINT PK_CERTIFIKAT_PRILOGA_PROIZVOD_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_PROIZVOD" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_PROIZVODCERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_PROIZVOD" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_PROIZVODPRILOGAID_PRILOGA"
   FOREIGN KEY (ID_PRILOGA)
   REFERENCES "PRILOGA" (ID);


CREATE TABLE "ESK_DATA"."CERTIFIKAT_PROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_CERTIFIKAT NUMBER,
	ID_PROIZVOD NUMBER,
	CONSTRAINT PK_CERTIFIKAT_PROIZVOD_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT_PROIZVOD" 
ADD CONSTRAINT "FK_CERTIFIKAT_PROIZVODCERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT_PROIZVOD" 
ADD CONSTRAINT "FK_CERTIFIKAT_PROIZVODPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);


CREATE TABLE "ESK_DATA"."PRILOGA_CLAN" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_PRILOGA NUMBER,
	ID_SUBJEKT NUMBER,
	CONSTRAINT PK_PRILOGA_CLAN_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."PRILOGA_CLAN" 
ADD CONSTRAINT "FK_PRILOGA_CLANPRILOGAID_PRILOGA"
   FOREIGN KEY (ID_PRILOGA)
   REFERENCES "PRILOGA" (ID);

ALTER TABLE "ESK_DATA"."PRILOGA_CLAN" 
ADD CONSTRAINT "FK_PRILOGA_CLANSUBJEKTID_SUBJEKT"
   FOREIGN KEY (ID_SUBJEKT)
   REFERENCES "SUBJEKT" (ID);


