# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: appProperties
  inputs:
    secureFile: 'application.properties'

- task: CmdLine@2
  inputs:
    script: 'cp $(appProperties.secureFilePath) api/src/main/resources'    

- task: CmdLine@2
  inputs:
    script: 'ls api/src/main/resources'

- task: Maven@3
  inputs:
    mavenPomFile: 'api/pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-DskipTests'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true    
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '/home/vsts/work/1/s/api/target/esk-notranji.war'
    ArtifactName: 'dropEskApi'
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '/home/vsts/work/1/s/templates'
    ArtifactName: 'dropEskTemplates'
