CREATE TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_CLAN" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_CERTIFIKAT NUMBER,
	ID_PRILOGA NUMBER,
	CONSTRAINT PK_CERTIFIKAT_PRILOGA_CLAN_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_CLAN" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_CLANCERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_CLAN" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_CLANPRILOGAID_PRILOGA"
   FOREIGN KEY (ID_PRILOGA)
   REFERENCES "PRILOGA" (ID);

