CREATE TABLE "ESK_DATA"."PROIZVODKOLICINE" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	VREDNOST NUMBER,
	ENOTA VARCHAR2(2000) NULL,
	LETO NUMBER,
	ID_PROIZVOD NUMBER NOT NULL,
	ID_CERTIFIKAT NUMBER NOT NULL,
	CONSTRAINT PK_PROIZVODKOLICINE_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."PROIZVODKOLICINE" 
ADD CONSTRAINT "FK_PROIZVODKOLICINEPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);

ALTER TABLE "ESK_DATA"."PROIZVODKOLICINE" 
ADD CONSTRAINT "FK_PROIZVODKOLICINECERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);

