CREATE TABLE "ESK_DATA"."UPORABNIK_PRAVICE" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_UPORABNIK NUMBER,
	ID_PRAVICA NUMBER,
	CONSTRAINT PK_UPORABNIK_PRAVICE_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."UPORABNIK_PRAVICE" 
ADD CONSTRAINT "FK_UPORABNIK_PRAVICEUPORABNIKID_UPORABNIK"
   FOREIGN KEY (ID_UPORABNIK)
   REFERENCES "UPORABNIK" (ID);

ALTER TABLE "ESK_DATA"."UPORABNIK_PRAVICE" 
ADD CONSTRAINT "FK_UPORABNIK_PRAVICEPRAVICAID_PRAVICA"
   FOREIGN KEY (ID_PRAVICA)
   REFERENCES "PRAVICA" (ID);

