CREATE TABLE "ESK_DATA"."UPORABNIK" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	UPORABNISKO_IME VARCHAR2(2000),
	IME VARCHAR2(2000),
	PRIIMEK VARCHAR2(2000),
	ORGANIZACIJA VARCHAR2(2000),
	TOKEN VARCHAR2(2000),
	CONSTRAINT PK_UPORABNIK_ID PRIMARY KEY (ID)
);
