CREATE TABLE "ESK_DATA"."ZASCITNIZNAK" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ZZ_SHEMA VARCHAR2(2000) NULL,
	NAZIV_PROIZVODA VARCHAR2(2000) NULL,
	DAT_ODL DATE NULL,
	ST_ODL VARCHAR2(2000) NULL,
	CERT_ORGAN VARCHAR2(2000) NULL,
	ID_IMETNIK NUMBER NOT NULL,
	ID_SHEMA NUMBER NOT NULL,
	ID_ZASCITEN_PROIZVOD NUMBER NOT NULL,
	CONSTRAINT PK_ZASCITNIZNAK_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."ZASCITNIZNAK" 
ADD CONSTRAINT "FK_ZASCITNIZNAKSUBJEKTID_IMETNIK"
   FOREIGN KEY (ID_IMETNIK)
   REFERENCES "SUBJEKT" (ID);

ALTER TABLE "ESK_DATA"."ZASCITNIZNAK" 
ADD CONSTRAINT "FK_ZASCITNIZNAKSHEMAID_SHEMA"
   FOREIGN KEY (ID_SHEMA)
   REFERENCES "SHEMA" (ID);

ALTER TABLE "ESK_DATA"."ZASCITNIZNAK" 
ADD CONSTRAINT "FK_ZASCITNIZNAKZASCITENPROIZVODID_ZASCITEN_PROIZVOD"
   FOREIGN KEY (ID_ZASCITEN_PROIZVOD)
   REFERENCES "ZASCITENPROIZVOD" (ID);

