CREATE TABLE "ESK_DATA"."CERTIFIKAT" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	TIP VARCHAR2(2000),
	STEVILKA VARCHAR2(2000),
	DAT_KONTROLE DATE NULL,
	DAT_IZDAJE DATE NULL,
	DAT_VELJ DATE NULL,
	STATUS VARCHAR2(2000),
	TEL_ST VARCHAR2(2000) NULL,
	EMAIL VARCHAR2(2000) NULL,
	OPOMBA CLOB NULL,
	DAT_VNOSA DATE,
	KONTROLOR VARCHAR2(2000),
	ID_SHEMA NUMBER NOT NULL,
	ID_ZASCITEN_PROIZVOD NUMBER NOT NULL,
	ID_PROIZVOD NUMBER NOT NULL,
	ID_IMETNIK NUMBER NOT NULL,
	ID_UPORABNIK NUMBER NOT NULL,
	ID_DEJAVNOST NUMBER NOT NULL,
	CONSTRAINT PK_CERTIFIKAT_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATSHEMAID_SHEMA"
   FOREIGN KEY (ID_SHEMA)
   REFERENCES "SHEMA" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATZASCITENPROIZVODID_ZASCITEN_PROIZVOD"
   FOREIGN KEY (ID_ZASCITEN_PROIZVOD)
   REFERENCES "ZASCITENPROIZVOD" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATSUBJEKTID_IMETNIK"
   FOREIGN KEY (ID_IMETNIK)
   REFERENCES "SUBJEKT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATUPORABNIKID_UPORABNIK"
   FOREIGN KEY (ID_UPORABNIK)
   REFERENCES "UPORABNIK" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT" 
ADD CONSTRAINT "FK_CERTIFIKATDEJAVNOSTID_DEJAVNOST"
   FOREIGN KEY (ID_DEJAVNOST)
   REFERENCES "DEJAVNOST" (ID);

