CREATE TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_PROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_CERTIFIKAT NUMBER,
	ID_PRILOGA NUMBER,
	CONSTRAINT PK_CERTIFIKAT_PRILOGA_PROIZVOD_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_PROIZVOD" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_PROIZVODCERTIFIKATID_CERTIFIKAT"
   FOREIGN KEY (ID_CERTIFIKAT)
   REFERENCES "CERTIFIKAT" (ID);

ALTER TABLE "ESK_DATA"."CERTIFIKAT_PRILOGA_PROIZVOD" 
ADD CONSTRAINT "FK_CERTIFIKAT_PRILOGA_PROIZVODPRILOGAID_PRILOGA"
   FOREIGN KEY (ID_PRILOGA)
   REFERENCES "PRILOGA" (ID);

