CREATE TABLE "ESK_DATA"."PRILOGA_CLAN" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_PRILOGA NUMBER,
	ID_SUBJEKT NUMBER,
	CONSTRAINT PK_PRILOGA_CLAN_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."PRILOGA_CLAN" 
ADD CONSTRAINT "FK_PRILOGA_CLANPRILOGAID_PRILOGA"
   FOREIGN KEY (ID_PRILOGA)
   REFERENCES "PRILOGA" (ID);

ALTER TABLE "ESK_DATA"."PRILOGA_CLAN" 
ADD CONSTRAINT "FK_PRILOGA_CLANSUBJEKTID_SUBJEKT"
   FOREIGN KEY (ID_SUBJEKT)
   REFERENCES "SUBJEKT" (ID);

