CREATE TABLE "ESK_DATA"."ZASCITNIZNAK_PROIZVOD" 
(	
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ID_ZASCITNIZNAK NUMBER,
	ID_PROIZVOD NUMBER,
	CONSTRAINT PK_ZASCITNIZNAK_PROIZVOD_ID PRIMARY KEY (ID)
);
ALTER TABLE "ESK_DATA"."ZASCITNIZNAK_PROIZVOD" 
ADD CONSTRAINT "FK_ZASCITNIZNAK_PROIZVODZASCITNIZNAKID_ZASCITNIZNAK"
   FOREIGN KEY (ID_ZASCITNIZNAK)
   REFERENCES "ZASCITNIZNAK" (ID);

ALTER TABLE "ESK_DATA"."ZASCITNIZNAK_PROIZVOD" 
ADD CONSTRAINT "FK_ZASCITNIZNAK_PROIZVODPROIZVODID_PROIZVOD"
   FOREIGN KEY (ID_PROIZVOD)
   REFERENCES "PROIZVOD" (ID);

