GRANT SELECT ON APP_ADMIN.ESK_SUBJ TO ESK_DATA;
GRANT SELECT ON APP_ADMIN.ESK_KMG_NOSILEC TO ESK_DATA;
GRANT SELECT ON APP_ADMIN.ESK_USERS TO ESK_DATA;
GRANT SELECT ON APP_ADMIN.ESK_KMG_ISAD_AREA TO ESK_DATA;
GRANT EXECUTE ON APP_ADMIN.ESK_PKG TO ESK_DATA;
GRANT SELECT ON SIR.ZAKOL_PO_GMID_ESK to ESK_DATA;
GRANT SELECT ON AKTRP_INTEGRACIJE.EV_MLEKO to ESK_DATA;

GRANT SELECT ON APP_ADMIN.ESK_SUBJ TO APP_ESK_N;
GRANT SELECT ON APP_ADMIN.ESK_KMG_NOSILEC TO APP_ESK_N;
GRANT SELECT ON APP_ADMIN.ESK_USERS TO APP_ESK_N;
GRANT SELECT ON APP_ADMIN.ESK_KMG_ISAD_AREA TO APP_ESK_N;
GRANT EXECUTE ON APP_ADMIN.ESK_PKG TO APP_ESK_N;
GRANT SELECT ON SIR.ZAKOL_PO_GMID_ESK to APP_ESK_N;
GRANT SELECT ON AKTRP_INTEGRACIJE.EV_MLEKO to APP_ESK_N;